---
- hosts: localhost
  connection: local
  vars:
    guid_v3: "{{ lookup('env', 'GUID_3') }}"
    guid_v4: "{{ lookup('env', 'GUID_4') }}"
    subdomain: "{{ lookup('env', 'DOMAIN') |d('events.opentlc.com') }}"
    username: "{{ lookup('env', 'USER') |d('lab_user') }}"
  tasks:
  - block:
      - name: "Adding new CORS rules"
        lineinfile:
          insertafter: "corsAllowedOrigins:"
          line: "- (?i)//migration-mig\\.apps\\.{{ guid_v4 }}\\.{{ subdomain }}"
          path: /etc/origin/master/master-config.yaml
        become: yes

      - name: "Checking if atomic-openshift services exist"
        shell: "systemctl status atomic-openshift-master-api"
        register: status
        become: yes
        ignore_errors: yes
      
      - name: "Applying new configuration [atomic-openshift services]"
        service:
          name: "{{ item }}"
          state: restarted
        loop:
          - atomic-openshift-master-api
          - atomic-openshift-master-controllers
        become: yes
        when: status.rc == 0
      
      - name: "Applying new configuration [master-restart]" 
        shell: "/usr/local/bin/master-restart {{ item }}"
        loop:
          - api
          - controller
        when: status.rc != 0
        become: yes
    delegate_to: "master1.{{ guid_v3 }}.{{ subdomain }}"
    vars:
      ansible_user: "ec2-user"
      ansible_ssh_private_key_file: "/home/{{ username }}/.ssh/openshift_key"
